### PR TITLE
Upgrade rouge to 2.0.7

### PR DESCRIPTION
**Pull request by hibariya**
Hello. Thank you for the nice integration gem!

Since there are [new lexers and fixes](https://github.com/jneen/rouge/blob/master/CHANGELOG.md#version-207-2016-11-18) which were added after rouge-0.8,  I'd love to use html-pipeline-rouge_filter with latest rouge (2.0.7).

The API of rouge has been changed since 2.0.0. Although I'm not sure how to deal with these [new formatters](https://github.com/jneen/rouge#formatters) via this filter, it seems possible to upgrade rouge without making API changes by using `Rouge::Formatters::HTMLLegacy` for now. This Pull Request does it.

What do you think? Let me know your opinion.

### CODE REVIEW

**Comment by JuanitoFatas** [comment]
> The API of rouge has been changed since 2.0.0. Although I'm not sure how to deal with these new formatters via this filter, it seems possible to upgrade rouge without making API changes by using Rouge::Formatters::HTMLLegacy for now. This Pull Request does it.

Good for now 👍 

Oh wow, thanks so much for the upadtes, looks like CI-san is not happy 😂  Would you take a look into that 🙏

**Comment by hibariya** [comment]
> Oh wow, thanks so much for the upadtes, looks like CI-san is not happy  Would you take a look into that

Sure. I'll investigate that :raising_hand_woman:

**Comment by hibariya** [comment]
There are some gems which don't support certain old runtime. I've made   setting upper limit of these versions only if the runtime is not supported by latest gems (43096f3).

* activesupport-5.0.0 or later don't support ruby < 2.1.0.
* Latest activesupport (5.0.2) doesn't support ruby < 2.2.2.
* nokogiri-1.7.0 or later don't support ruby < 2.1.0.

**Comment by JuanitoFatas** [comment]
Thanks so much for the hard work!!!!! 👍 💯 

Do you want to be a committer of this project? 👩🏻‍💻

**Comment by JuanitoFatas** [comment]
Shipped in v1.0.5!!! 🐑

**Comment by hibariya** [comment]
Thanks!!!!!

> Do you want to be a committer of this project? 👩🏻‍💻

Yes I do :smile_cat: It's an honor.

**Pull request merged**
